### PR TITLE
Practice-app: Formula 1 API

### PR DESCRIPTION
**Pull request by eceasslan**
Created Formula 1 API and its corresponding HTML files. Wondering if everything is fine with my API, so waiting for your reviews.

### CODE REVIEW

**Comment by yigitsarioglu** [comment]
I checked your code, I don't see anything wrong with your code.. You should also create unittest for your api. Also you may add your api name and its url to apiOverview method in views.py.

**Comment by ihsanmertatalay** [comment]
I looked your code it will work correctly.

**Comment by eceasslan** [comment]
> I checked your code, I don't see anything wrong with your code.. You should also create unittest for your api. Also you may add your api name and its url to apiOverview method in views.py.

I created unit tests and added my API name and its url to apiOverview method.

**Comment by kerimoglutolga** [comment]
I have fixed the conflict in urls.py and merging this.

**Comment by berkaygumus** [comment]
Your API works properly. Maybe it could be better if we search for drivers with Latin alphabet, too. I mean when I write Raikkonen rather than Räikkönen, it says "there is no driver".  But I think it is not a big issue. Your API is enjoyable and cool for me as an F1 follower.

**Pull request merged**
