### PR TITLE
Berkaygumus

### PR DESCRIPTION
**Pull request by berkaygumus**
I have created a page giving the information about NBA teams using nba-api. I have added html files and api files. I have updated view.py, urls.py and requirements.txt. Could you review my api and check whether it works properly?

### CODE REVIEW

**Comment by yigitsarioglu** [comment]
I check your code, I couldn't see any thing wrong with your code.. it looks fine.

**Comment by kerimoglutolga** [comment]
I have resolved 2 conflicts in urls.py and views.py where you were not synchnorized with a side branch but nothing too important.

**Comment by mehmethilmidundar** [comment]
I've also checked your code, it works correctly. I don't find any input case which program fails in this case so  your code seems nice.

**Comment by yagmurse** [comment]
I run your test cases and it worked fine

**Pull request merged**
