### PR TITLE
Holidays api

### PR DESCRIPTION
**Pull request by mehmethilmidundar**
I have added html file, api python files and unit test file. I've also cahanged the urls.py and views.py.  You can check and overview my code.

### CODE REVIEW

**Comment by yagmurse** [comment]
I couldn't understand the conflicts for your branch. Are you getting any errors now while running app?

**Comment by mehmethilmidundar** [comment]
> I couldn't understand the conflicts for your branch. Are you getting any errors now while running app?

No, it runs correctly in my computer. I've also runned the other apis and so the binary pyc files of these api's are changed and i commit these also. Probably, it is the reason of the conflict. But i will appreciate, if you run my api in your computer and say results to me. I try to handle conflicts.

**Comment by kerimoglutolga** [comment]
The cache files don't need to be tracked. You can exclude them from your branch using git rm --cached 'filename' or use gitignore.

**Comment by eceasslan** [comment]
> > I couldn't understand the conflicts for your branch. Are you getting any errors now while running app?
> 
> No, it runs correctly in my computer. I've also runned the other apis and so the binary pyc files of these api's are changed and i commit these also. Probably, it is the reason of the conflict. But i will appreciate, if you run my api in your computer and say results to me. I am tryng to handle conflicts.

I tried your code. It works properly in my computer.

**Comment by kerimoglutolga** [comment]
I have resolved 2 simple conflicts, looks fine otherwise.

**Pull request merged**
