### PR TITLE
Pull branch 'salih'

### PR DESCRIPTION
**Pull request by salihfurqan**
This branch has implemented only the test part of the 'random_article' api which only gets a Wikipedia article on a sports arena. I want members to review other parts of it since it had been pushed to the 'dev' directly altogether before. Also, I'd appreciate 'eq_post' api be reviewed by other members, the other api I had pushed to the 'dev' branch. The 'eq_post' api tries to establish a template for equipment posts, going a similar way with the 'register' api.
This branch also pushes a new requirements.txt that includes 'googlemaps' since it is needed for another api by another member.
Thanks in advance!

### CODE REVIEW

**Comment by kerimoglutolga** [comment]
I don't see anything wrong with the code but the test is to check that the server returns an error (HTTP_400_BAD_REQUEST) if it returns an empty article. This is not a proper way to check for whether the returned response is empty or not. Instead you should be confirming that the API won't return an error in general.

**Comment by salihfurqan** [comment]
I added a response to the main api to go in line with the test already provided after the comment by kerimoglutolga.

**Comment by yigitsarioglu** [comment]
I also checked your code and couldn't see anything wrong with the code.

**Comment by yagmurse** [comment]
I  checked your code and as far as my current code knowledge, I couldn't see anything wrong.

**Pull request merged**
